### ISSUE TITLE
Unable to add bot to server

### ISSUE THREAD

**Issue by shshdhdhdhdyx** [jseery-2076714/TOUB#17]
I've been trying to add the bot using the given instructions in user_manual.txt, but when I copy-paste the URL, it just redirects me back to the friends page on Discord.
To reproduce the bug, copy-paste the URL given in user-manual.txt. The expected outcome is that you're redirected to a page where you can choose which server(s) to add the bot to, but the actual outcome is that you're redirected to the friends page on DIscord.

**Comment by tu21897** [comment]
Try this link:
https://discord.com/api/oauth2/authorize?client_id=970509633179492393&permissions=8&scope=bot

Should also be updated in the user manual
